#!/usr/bin/env python

"""
Usage: prog <num spark nodes> <service-name> <log-location> <callback>

Action: Calls script that creates spark cluster and launches spark workflow

Assumptions:
    1.The environment should be properly set by the driver.
    2. spark_launch should be in the executable path
"""

import sys
import os


# use current environment and launch with number of machines (1 for master)
# (ADD CUSTOM NON-BLOCKING CALL TO LAUNCH SCRIPT ON SPARK MASTER!!)
command = "qsub -jc spark -pe spark " + str(int(sys.argv[1])+1) + " -q hadoop2 -j y -V -o " + sys.argv[2]+".wrapper.log" + " -m b spark_launch "

# add python script location and its configuration file
command += " ".join(sys.argv[2:])

os.system(command)

